services:
  webhook-server:
    build: .
    command:
      - -misskey-hook-secret=${MISSKEY_HOOK_SECRET:?MISSKEY_HOOK_SECRET is required}
      - -misskey-host=${MISSKEY_HOST:?MISSKEY_HOST is required}
      - -misskey-token=${MISSKEY_TOKEN:?MISSKEY_TOKEN is required}
      - -misskey-media-host=${MISSKEY_MEDIA_HOST:?MISSKEY_MEDIA_HOST is required}
      - -twitter-media-hosts=${TWITTER_MEDIA_HOSTS:-pbs.twimg.com,video.twimg.com}
      - -twitter-api-key=${TWITTER_API_KEY:?TWITTER_API_KEY is required}
      - -twitter-api-key-secret=${TWITTER_API_KEY_SECRET:?TWITTER_API_KEY_SECRET is required}
      - -twitter-access-token=${TWITTER_ACCESS_TOKEN:?TWITTER_ACCESS_TOKEN is required}
      - -twitter-access-token-secret=${TWITTER_ACCESS_TOKEN_SECRET:?TWITTER_ACCESS_TOKEN_SECRET is required}
      - -twitter-user-access-token=${TWITTER_USER_ACCESS_TOKEN:?TWITTER_USER_ACCESS_TOKEN is required}
      - -twitter-webhook-consumer-secret=${TWITTER_WEBHOOK_CONSUMER_SECRET:-}
      - -twitter-username=${TWITTER_USERNAME:-}
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - './data:/app/data'
