services:
  webhook-server:
    build: .
    command:
      - -misskey-hook-secret=${MISSKEY_HOOK_SECRET:?MISSKEY_HOOK_SECRET is required}
      - -misskey-host=${MISSKEY_HOST:?MISSKEY_HOST is required}
      - -misskey-token=${MISSKEY_TOKEN:?MISSKEY_TOKEN is required}
      - -misskey-media-host=${MISSKEY_MEDIA_HOST:?MISSKEY_MEDIA_HOST is required}
      - -twitter-media-hosts=${TWITTER_MEDIA_HOSTS:-pbs.twimg.com,video.twimg.com}
      - -twitter-oauth2-client-id=${TWITTER_OAUTH2_CLIENT_ID:?TWITTER_OAUTH2_CLIENT_ID is required}
      - -twitter-oauth2-redirect-url=${TWITTER_OAUTH2_REDIRECT_URL:?TWITTER_OAUTH2_REDIRECT_URL is required}
      - -twitter-token-store-path=${TWITTER_TOKEN_STORE_PATH:-data/twitter_oauth2_token.json}
      - -twitter-bearer-token=${TWITTER_BEARER_TOKEN:?TWITTER_BEARER_TOKEN is required}
      - -twitter-stream-keep-alive-timeout=${TWITTER_STREAM_KEEP_ALIVE_TIMEOUT:-90s}
      - -twitter-username=${TWITTER_USERNAME:?TWITTER_USERNAME is required}
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - './data:/app/data'
