apiVersion: v2
name: note-tweet-connector
description: A Helm chart for the Note Tweet Connector
type: application
sources:
  - https://github.com/Soli0222/note-tweet-connector
version: 2.3.2
appVersion: 3.4.2
