apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-tweet-connector-deployment
  labels:
    app: note-tweet-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: note-tweet-connector
  template:
    metadata:
      labels:
        app: note-tweet-connector
    spec:
      containers:
        - name: app
          image: soli0222/note-tweet-connector:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: MISSKEY_HOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: note-tweet-connector-secret
                  key: MISSKEY_HOOK_SECRET
            - name: IFTTT_HOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: note-tweet-connector-secret
                  key: IFTTT_HOOK_SECRET
            - name: MISSKEY_HOST
              valueFrom:
                secretKeyRef:
                  name: note-tweet-connector-secret
                  key: MISSKEY_HOST
            - name: MISSKEY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: note-tweet-connector-secret
                  key: MISSKEY_TOKEN
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: note-tweet-connector-secret
                  key: API_KEY
            - name: API_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: note-tweet-connector-secret
                  key: API_KEY_SECRET
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: note-tweet-connector-secret
                  key: ACCESS_TOKEN
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: note-tweet-connector-secret
                  key: ACCESS_TOKEN_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: note-tweet-connector-service
spec:
  selector:
    app: note-tweet-connector
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080